# Generated by Django 3.1.4 on 2021-01-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='公司', max_length=64)),
                ('country', models.CharField(help_text='国家', max_length=64)),
                ('region', models.CharField(help_text='地区', max_length=64)),
                ('industry', models.CharField(help_text='行业', max_length=64)),
                ('description', models.CharField(help_text='名称', max_length=64, unique=True)),
                ('part_number', models.CharField(help_text='型号', max_length=120, unique=True)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('manufacturing_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('special_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '成本明细',
                'verbose_name_plural': '成本明细',
                'ordering': ['company'],
            },
        ),
    ]
