# Generated by Django 3.1.4 on 2020-12-29 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Costmodel Title', max_length=120)),
                ('part_number', models.CharField(help_text='Part Number', max_length=120)),
                ('company', models.CharField(help_text='Company', max_length=120)),
                ('overhead', models.DecimalField(blank=True, decimal_places=2, help_text='Example: Enter 10 for 10% Overhead', max_digits=6, null=True, verbose_name='Overhead (%)')),
                ('packaging', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('freight', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('customs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tooling', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, help_text='Example: Enter 5 for 5% Profit', max_digits=6, null=True, verbose_name='Profit (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cost breakdown',
                'verbose_name_plural': 'cost breakdowns',
                'ordering': ['title'],
                'permissions': (('download_cost_breakdown', 'Can download cost breakdown in excel and pdf'), ('manage_cost_breakdown', 'Can manage own cost breakdown'), ('manage_library', 'Can manage standard cost breakdown library')),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MaterialBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Material Title', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('scrap', models.DecimalField(blank=True, decimal_places=2, help_text='Example: Enter 1 for 1% Scrap', max_digits=6, null=True, verbose_name='Scrap (%)')),
                ('overhead', models.DecimalField(blank=True, decimal_places=2, help_text='Example: Enter 3 for 3% Overhead', max_digits=6, null=True, verbose_name='Overhead (%)')),
                ('costbreakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.costbreakdown')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.unit')),
            ],
            options={
                'verbose_name': 'material breakdown',
                'verbose_name_plural': 'material breakdowns',
                'ordering': ['costbreakdown', 'title', '-price'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(help_text='Manufacturing Process Step', max_length=120)),
                ('labor_quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('labor_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('machine_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Machine hourly rate', max_digits=8)),
                ('cycle_time', models.DecimalField(decimal_places=2, help_text='Number of minutes of cycle time', max_digits=6)),
                ('parts', models.IntegerField(default=1)),
                ('scrap', models.DecimalField(blank=True, decimal_places=2, help_text='Example: Enter 1 for 1% Scrap', max_digits=6, null=True, verbose_name='Scrap (%)')),
                ('overhead', models.DecimalField(blank=True, decimal_places=2, help_text='Example: Enter 30 for 30% Overhead', max_digits=6, null=True, verbose_name='Overhead (%)')),
                ('setup', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('costbreakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.costbreakdown')),
            ],
            options={
                'verbose_name': 'manufacturing breakdown',
                'verbose_name_plural': 'manufacturing breakdowns',
                'ordering': ['costbreakdown', 'process_step'],
            },
        ),
    ]
