# Generated by Django 3.1.4 on 2021-01-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='物料名称', max_length=64, unique=True)),
                ('part_number', models.CharField(help_text='物料型号', max_length=120, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('usage', models.DecimalField(decimal_places=2, default=1.0, max_digits=12)),
                ('indirect_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loss_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Example: Enter 1 for 1% Loss_Rate', max_digits=6, null=True, verbose_name='Loss_Rate (%)')),
                ('material_overhead_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Example: Enter 3 for 3% Material_Overhead_Rate', max_digits=6, null=True, verbose_name='Material_Overhead_Rate (%)')),
                ('costbreakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.costbreakdown')),
            ],
            options={
                'verbose_name': '物料明细',
                'verbose_name_plural': '物料明细',
                'ordering': ['costbreakdown', 'description', '-price'],
            },
        ),
    ]
