# Generated by Django 3.1.4 on 2021-01-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overheadbreakdown',
            name='administration_overhead_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Example: Enter 3 for 3% Administration_Overhead_Rate', max_digits=6, null=True, verbose_name='Administration_Overhead_Rate (%)'),
        ),
        migrations.AddField(
            model_name='overheadbreakdown',
            name='logistics_overhead_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Example: Enter 3 for 3% Logistics_Overhead_Rate', max_digits=6, null=True, verbose_name='Logistics_Overhead_Rate (%)'),
        ),
        migrations.AddField(
            model_name='overheadbreakdown',
            name='sales_overhead_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Example: Enter 3 for 3% Sales_Overhead_Rate', max_digits=6, null=True, verbose_name='Sales_Overhead_Rate (%)'),
        ),
        migrations.AlterField(
            model_name='costbreakdown',
            name='part_number',
            field=models.CharField(help_text='型号', max_length=120),
        ),
        migrations.AlterField(
            model_name='overheadbreakdown',
            name='development_overhead_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Example: Enter 3 for 3% Development_Overhead_Rate', max_digits=6, null=True, verbose_name='Development_Overhead_Rate (%)'),
        ),
    ]
