# Generated by Django 3.1.4 on 2021-01-23 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0002_auto_20210122_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costbreakdown',
            options={'ordering': ['company'], 'verbose_name': '总成本明细', 'verbose_name_plural': '总成本明细'},
        ),
        migrations.AlterModelOptions(
            name='overheadbreakdown',
            options={'ordering': ['costbreakdown'], 'verbose_name': '管理成本明细', 'verbose_name_plural': '管理成本明细'},
        ),
        migrations.RemoveField(
            model_name='costbreakdown',
            name='special_cost',
        ),
        migrations.CreateModel(
            name='SpecialBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('freight_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('duty_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tooling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tooling_quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=12)),
                ('manufacturing_parts', models.DecimalField(decimal_places=2, default=1.0, max_digits=12)),
                ('costbreakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.costbreakdown')),
            ],
            options={
                'verbose_name': '其它成本明细',
                'verbose_name_plural': '其它成本明细',
                'ordering': ['costbreakdown'],
            },
        ),
    ]
