# Generated by Django 3.1.4 on 2021-01-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0004_auto_20210123_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costbreakdown',
            name='company',
            field=models.CharField(help_text='公司', max_length=64, verbose_name='公司'),
        ),
    ]
