# Generated by Django 3.1.4 on 2021-01-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0005_auto_20210124_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costbreakdown',
            name='company',
            field=models.CharField(max_length=64, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='costbreakdown',
            name='country',
            field=models.CharField(max_length=64, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='costbreakdown',
            name='description',
            field=models.CharField(max_length=64, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='costbreakdown',
            name='industry',
            field=models.CharField(max_length=64, verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='costbreakdown',
            name='manufacturing_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='costbreakdown',
            name='part_number',
            field=models.CharField(max_length=120, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='costbreakdown',
            name='profit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='例如：输入5就是5%的利润率', max_digits=6, null=True, verbose_name='利润率（%）'),
        ),
        migrations.AlterField(
            model_name='costbreakdown',
            name='region',
            field=models.CharField(max_length=64, verbose_name='地区'),
        ),
    ]
