# Generated by Django 3.1.4 on 2021-01-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0006_auto_20210124_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costbreakdown',
            name='manufacturing_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='制造成本'),
        ),
    ]
